@extends('layout.app')

@section('title','Hidden Parts of Northeast')


@section('body')
<div class="site-section">
    <div class="container ">
      <div class="row mb-3 align-items-stretch">
        <div class="col-md-12">
            <div class="title-classic-title">
              <h3 style="margin-top:50px;">Hidden parts of Northeast that<br> can’t be seen from your hotel window.</h3>
            </div>
            <div class="meta mb-4" style="margin-top:20px;">June 04, 2019 </div>
            <div class="text-left">
            <img src="images/northeast.jpg" alt="Image" class="img-fluid" style="margin-bottom:30px;margin-top:30px;">
            <p class="justify">Scenic, unexplored, wild, captivating – these are the things that come to our minds when we think of Northeast India, isn’t it? It’s true the region has had a huge number of visitors (and still counting) owing to its picturesque charm and pleasant weather; often on the lower side of temperature.</p>
            <p class="justify">But every time you think you have seen (or heard) of all there is to Northeast, Instagram hits you with yet another picture of the region that completely blows your mind. We like to think of it as a gift that just keeps giving! </p>
            <p><br></p>
            <h4>Where’s all that magic hiding?</h4>
            <img src="images/magichiding.jpg" alt="Image" class="img-fluid" style="margin-top:30px;margin-bottom:30px;">
            <p class="justify">Be it Arunachal Pradesh or Nagaland, travelling to Northeast requires a little more than just a hotel booking; that is, if you wish to see the unseen, and connect with nature on a spiritual level. Yes, it’s worth every bit of you leaving your linen comfort back at the hotel.</p>
            <p class="justify">The touristy things to do here involves gearing up for a trek, visiting a local village, trying out delicious ethnic cuisines, bask in the beauty of gorgeous waterfalls and lakes; caves and hilly trails; scenic villages and tea gardens; wildlife sanctuaries, and the list goes on.</p>
            <p class="justify"><br></p>
            <h4>Camping in the Northeast.</h4>
            <img src="images/campinginnortheast.jpg" alt="Image" class="img-fluid" style="margin-top:30px;margin-bottom:30px;">
            <p class="justify">If you’re travelling to Northeast, you can’t afford to miss out on the stunning landscapes beautifully preserved by its people here. And that means, the closer you’re to nature, more rewarding your experience gets. And what’s better than camping right in the middle of picturesque setting of the region. At Encamp, we cover a total of 22 beautiful camp sites spread across the Northeast, and we are working towards adding on more to the list. </p>
            <p class="justify">Whether you want to experience ‘floating boats in the air’ at Dawki, relax beside the pristine Krangsuri waterfalls in Meghalaya, trek down the breath-taking Dzukou Valley in Nagaland or simply plan a quick weekend getaway at a Hillside camp in Guwahati, our team at Encamp likes to ensure that all our travelers get to experience a one-of-a-kind holiday as per their choice of destination and activities. </p>
            <p class="justify">Few of our other campsites are present in Dirang (Arunachal Pradesh), Darrang (Meghalaya), Kaziranga (Assam), Shnongpdeng (Meghalaya) and many more, in exotic locations which often leave our travelers with a delightful experience to take back home.</p>
            <p><br></p>
            <h4>We travel responsibly.</h4>
            <img src="images/travelresponsibly.jpg" alt="Image" class="img-fluid" style="margin-top:30px;margin-bottom:30px;">
            <p class="justify">One of the major concerns surrounding tourism is the amount of waste generated by tourists during their trip. Northeast is home to some of the cleanest villages and we intend on keeping it that way. This is why, when you take a trip with us, you’ll notice that we try minimizing waste as much as possible by using eco-friendly products, minimal use of disposable plastic, and so on.</p>
            <p class="justify">Talk to us here, to know about the facilities we offer at our campsites, so that you can pack only the things essential to you and travel light. This helps a lot in making your journey more relaxed and cuts down the amount of waste left behind after the trip is over.</p>
            <p><br></p>
            <h4>Indulging in music festivals of Northeast</h4>
            <img src="images/musicfestival.jpg" alt="Image" class="img-fluid" style="margin-top:30px;margin-bottom:30px;">
            <p class="justify">Every year, tons of people fly down to this part of India, not only to explore the region, but to also imbibe the essence of some of the best music and cultural festivals that takes place annually in the region.</p>
            <p class="justify">Talking of music festivals, the gorgeous Ziro Valley in Arunachal Pradesh is popular for the annual Ziro Festival of Music event, organized by the Apatani tribe of the region. This year, it’s set to take place from 26th to 29th September 2019.</p>
            <p class="justify"><i>Going to Ziro Festival of Music? Book your stay with us here.</i></p>
            <p class="justify">We host annual camps during these music festivals such as the Ziro Festival of Music in Arunachal Pradesh, NH7 Weekender in Meghalaya, Orange festival of Adventures and Music in Dambuk, Arunachal Pradesh, the famed Hornbill Festival in Nagaland, and so on. People attending these festivals love exploring the scenic places around, and indulge in the cultural vibes through meeting local people and trying out their ethnic cuisines.</p>
            <p class="justify">As it turns out, camping offers one of the best possibilities to explore the local region while staying in sync with nature. We have had some of the best moments with our travelers, when we see them experience something new, every time they travel with us.</p>
            <p class="justify">Have a trip in mind? Connect with us here.</p>
            <br><br>
            
            <div id="disqus_thread"></div>
            <script>
        
            /**
            *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
            *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
            /*
            var disqus_config = function () {
            this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
            this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
            };
            */
            (function() { // DON'T EDIT BELOW THIS LINE
            var d = document, s = d.createElement('script');
            s.src = 'https://http-www-encampadventures-com.disqus.com/embed.js';
            s.setAttribute('data-timestamp', +new Date());
            (d.head || d.body).appendChild(s);
            })();
            </script>
            <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
            <br><br><br>
            </div>
          </div>
        </div>


      </div>
  </div>

@endsection
